export enum Language {
    'ar' = 'ar',
    'de' = 'de',
    'en' = 'en',
    'es' = 'es',
    'fr' = 'fr',
    'he' = 'he',
    'it' = 'it',
    'nl' = 'nl',
    'no' = 'no',
    'pt' = 'pt',
    'ru' = 'ru',
    'sv' = 'sv',
    'ud' = 'ud',
    'zh' = 'zh',
}
