name: Check
on:
  pull_request:
    branches: [ master, development ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install modules
        run: yarn install

      - name: Eslint
        run: yarn lint
